//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleServicesAPP.Resources.Database.Pharmacy {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoredProcedureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultipleServicesAPP.Resources.Database.Pharmacy.StoredProcedureResources", typeof(StoredProcedureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @description.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @descriptionCatalog.
        /// </summary>
        public static string descriptionCatalog {
            get {
                return ResourceManager.GetString("descriptionCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @expireDate.
        /// </summary>
        public static string expireDate {
            get {
                return ResourceManager.GetString("expireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @finishDate.
        /// </summary>
        public static string finishDate {
            get {
                return ResourceManager.GetString("finishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idCatalog.
        /// </summary>
        public static string idCatalog {
            get {
                return ResourceManager.GetString("idCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idItem.
        /// </summary>
        public static string idItem {
            get {
                return ResourceManager.GetString("idItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idMed.
        /// </summary>
        public static string idMed {
            get {
                return ResourceManager.GetString("idMed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idPresentation.
        /// </summary>
        public static string idPresentation {
            get {
                return ResourceManager.GetString("idPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idSale.
        /// </summary>
        public static string idSale {
            get {
                return ResourceManager.GetString("idSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @idUser.
        /// </summary>
        public static string idUser {
            get {
                return ResourceManager.GetString("idUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @imgUrl.
        /// </summary>
        public static string imgUrl {
            get {
                return ResourceManager.GetString("imgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @pricePerUnit.
        /// </summary>
        public static string pricePerUnit {
            get {
                return ResourceManager.GetString("pricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @registeredDate.
        /// </summary>
        public static string registeredDate {
            get {
                return ResourceManager.GetString("registeredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @startDate.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.stp_admin_sales.
        /// </summary>
        public static string stp_admin_sales {
            get {
                return ResourceManager.GetString("stp_admin_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbo.stp_admin_users.
        /// </summary>
        public static string stp_admin_users {
            get {
                return ResourceManager.GetString("stp_admin_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
