//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleServicesAPP.Resources.Database.WeatherIO {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WeatherResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultipleServicesAPP.Resources.Database.WeatherIO.WeatherResources", typeof(WeatherResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.weatherbit.io/v2.0/.
        /// </summary>
        public static string baseURL {
            get {
                return ResourceManager.GetString("baseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ?lat={0}&amp;lon={1}&amp;lang=es&amp;days=4&amp;key={2}.
        /// </summary>
        public static string concatenation {
            get {
                return ResourceManager.GetString("concatenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a current?lat=19.042157&amp;lon=-98.210131&amp;lang=es&amp;key=.
        /// </summary>
        public static string consumingDailyReportPuebla {
            get {
                return ResourceManager.GetString("consumingDailyReportPuebla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a forecast/daily.
        /// </summary>
        public static string consumingForHours {
            get {
                return ResourceManager.GetString("consumingForHours", resourceCulture);
            }
        }
    }
}
